title: Bryan Stanley Effendy
description: Machine Learning Engineer
theme: jekyll-theme-minimal

# Add this section below
params:
  github_username: Basa-glitch
  email: bryaneffendy317@gmail.com
  phone: "0813-1809-6578"

# Optional: To make them appear as links in your bio/header
social:
  - title: github
    url: https://github.com/Basa-glitch
  - title: email
    url: bryaneffendy317@gmail.com
