title: Bryan Stanley Effendy
description: Machine Learning Engineer
theme: jekyll-theme-minimal

# These are the variables your new default.html is looking for
email: "bryaneffendy317@gmail.com"
phone: "0813-1809-6578"
about_me: "Passionate ML Engineer focused on AI/Deep Learning. Experienced in research and education."
