title: Bryan Stanley Effendy
description: Machine Learning Engineer
theme: jekyll-theme-minimal
logo: NewIm.jpg

# These variables must match the names used in the HTML file above
email: "bryaneffendy317@gmail.com"
phone: "+62 813 1809 6578"
about_me: "A passionate Intelligent System Engineer focusing on Advancement of AI especially on Edge AI for Embedded system"
