title: Bryan Stanley Effendy
logo: 472x709px f.jpg
#description: Bookmark this to keep an eye on my project updates!
theme: jekyll-theme-architect

params:
  email: "bryaneffendy317@gmail.com"
  phone: "0813-1809-6578"
  
  social:
    - name: github
      url: "https://github.com/Basa-glitch"
    - name: email
      url: "bryaneffendy317@gmail.com"
    - name: phone
      url: "tel:0813-1809-6578"
