title: Bryan Stanley Effendy
description: Machine Learning Engineer
theme: jekyll-theme-minimal

# These variables must match the names used in the HTML file above
email: "your.email@example.com"
phone: "+62 123 4567 890"
about_me: "Passionate ML Engineer focused on AI/Deep Learning. Experienced in research and education. Eager to innovate."
